import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import type { Metadata } from "next";
import "./globals.css";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import ReduxProvider from "@/redux/ReduxProvider";
import Navbar from "@/components/navbar/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Await `params` properly
  const { locale } = await params;
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={`antialiased flex flex-col min-h-[100dvh] overflow-hidden`}
      >
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            <Navbar />
            <div className="flex-1 flex h-[calc(100dvh-80px)] mt-[80px]">
              {/* sidebar */}
              <Sidebar />
              {/* content */}
              <main className="flex-1 m-4 h-[calc(100dvh-80px-32px)] bg-gray-200 p-4 overflow-y-auto">
                {children}
              </main>
            </div>
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
